### PR TITLE
Feat/home everywhere

### PR DESCRIPTION
**Pull request by WebsByTodd**
Replace the header link to the homepage with the "more info" dropdown to all pages but the homepage.

### CODE REVIEW

**Comment by WebsByTodd** [comment]
@nedtwigg if you think there's a chance this will go stale, let me know. I can feature flag the the tabs so that they don't render while merging in the header change (moving it from rocker to react). I'll try to get to it within a week though.

**Comment by nedtwigg** [comment]
I expect GitFact will cause some merge conflicts in the server snapshots, but that's not a big problem.  If a feature flag is <15 mins, I would say feature flag and merge to be safe.  Hopefully we will be dev-launching on Tues or Wed.

**Comment by nedtwigg** [comment]
Two bugs, one style nit:

- [ ] Easy bug: fact titles seem to have a higher z-index than the popup
IMG_9664

- [ ] Harder bug: The popup is scrollable (good). The content behind the popup is *also* scrollable (bad). Depending on where the mouse is when you start the scroll, you either scroll the content within the popup, or you scroll the whole page and the popup goes away, and you're just looking at a darkened-version of the whole page

- [ ] Style nit: I think the popup would be easier to understand if it cast a drop shadow over the content

One possible solution to all of these would be for the popup to consume the entire screen.  I think it would be better for it to remain a partial popup, but if we can't fix all of these issues, then a fullscreen popup might be better.

**Review by nedtwigg — CHANGES_REQUESTED** [review]
See above.

**Pull request merged**
