### PR TITLE
Fix the search bug

### LINKED ISSUE #243: Search results should be sorted by date, and not have duplicates
As of `prod/2020-03-19`, https://mytake.org/search?q=social%20security returns

- Carter Reagan (1 of 1) 1980-10-28
- Mondale Reagan (1 of 2) 1984-10-07
- Carter Reagan (1 of 1) 1980-10-28 (second time!)
- Obama Romney (1 of 3) 2012-10-03
- McCain Obama (2 of 3) 2008-10-07
- Carter Reagan (1 of 1) 1980-10-28 (third time!!!)
- Bush Kerry (3 of 3) 2004-10-13
- Obama Romney (1 of 3) 2012-10-03
- Carter Reagan (1 of 1) 1980-10-28 (fourth time)
- Bush Kerry (3 of 3) 2004-10-13

...and that's just a third of the way through

### PR DESCRIPTION
**Pull request by nedtwigg**
Fixes #243.

- I made a test, `VideoResultsList.spec.tsx`, which mocks out the actual results from the server for the "social security" query described in #243 
- https://github.com/mytakedotorg/mytakedotorg/blob/6c83132b5d2edca689304ef5319534d11b18fb09/client/src/main/scripts/components/VideoResultsList.spec.tsx#L10-L18
- The `VideoResultsList` component fetches the relevant facts asynchronously, so the snapshot it generates is not useful
- https://github.com/mytakedotorg/mytakedotorg/blob/6c83132b5d2edca689304ef5319534d11b18fb09/client/src/main/scripts/components/__snapshots__/VideoResultsList.spec.tsx.snap#L13-L22
- I don't know how to test the logic without the asynchronous part.

I'm stuck :). But it looks like the problem is in the typescript side afterall.  When you have time, can you get me unstuck @WebsByTodd?  `npx jest src/main/scripts/components/VideoResultsList.spec.tsx --updateSnapshot` from the client dir is the command I'm planning on using to fix the typescript logic.

### CODE REVIEW

**Comment by nedtwigg** [comment]
@WebsByTodd if you can make it so that `client/src/main/scripts/components/__snapshots__/VideoResultsList.spec.tsx.snap` has search results, rather than `Search returned no results for ...` then I think I can take it from there.  Happy to work in realtime with you anytime.

Eventually, it does have the real search results there, but the snapshot happens too quickly (the component waits for the facts to load).

Related to this, it shouldn't say `Search returned no results`, it should say `Searching ...`, and then eventually have either the results or a message saying that there weren't any.  There's an opportunity to be pretty definitive here `"Foo bar" was never said during a United States Presidential debate.`

**Comment by nedtwigg** [comment]
Getting better!  The problem now is that the search results are not sorted by turn within the debate, especially jarring when questioner says "what about X" and the answer comes before the question. [e.g. social security](https://mytakedotorg-feat-fix-s-lusmvs.herokuapp.com/search?q=social%20security), see screenshot below.

Screen Shot 2020-07-12 at 11 18 00 PM

**Comment by WebsByTodd** [comment]
Ok, here's the fix for the turn order. The test case is actually more time consuming than the fix, so I put a stub in place. @nedtwigg can you either make this test case work or make an issue for it so that I don't forget about it? Thanks.

**Comment by nedtwigg** [comment]
Awesome, this works great!  I might be wrong, but I think `VideoResultsLoader.spec.tsx` was redundant with `VideoResultsList.spec.tsx`, it just did the snapshot manually rather than with `--updateSnapshots`.  The trouble is that the snapshot is going to be changing quite a bit as more transcripts get added / improved.

If I'm missing something, feel free to bring the test back in a new PR, or create an issue to track

**Pull request merged**
