### PR TITLE
Feature/node

### PR DESCRIPTION
**Pull request by WebsByTodd**

### CODE REVIEW

**Comment by nedtwigg** [comment]
Only thing left is to have some kind of smoketest that the node project still runs.  Bring up the server, give it an url, snapshot test the image result.  Ideally we can do a binary snapshot, but because of compression might be more reliable to use jest-image-snapshot.  I sank a bunch of time into trying to get node-canvas to compile with node 10.11, I got stuck.

According to the wiki: https://github.com/Automattic/node-canvas/wiki/Installation:-Prebuilt#install

> Canvas 2.x uses prebuilds by default when you run npm install canvas or yarn add canvas

So we should upgrade to that.

**Comment by nedtwigg** [comment]
I tried to add a smoketest, only to find that the project is definitely not in a compiling state.  I went back to 49cce1c.  Because `npm install` fails (can't get canvas to compile), I can't tell if it was in a compiling state before automating the client -> node transfer.

By upgrading to canvas 2.x, there are precompiled binaries and one batch of problems goes away.  But it looks to need a minor refactor in order for the next batch of problems to go away.  Happy to meet anytime to get this resolved.  I'm hesitant to move forward with anything else while this is unmerged, lest this PR gets buried by conflicts.

**Comment by nedtwigg** [comment]
Because this is async: https://github.com/mytakedotorg/mytakedotorg/blob/76f5a846ada209661c832b5169268fba425c70d4/node/src/main/scripts/app.ts#L17-L22

These tests are failing:
https://github.com/mytakedotorg/mytakedotorg/blob/feature/node/node/src/main/scripts/app.spec.ts#L7

Test aside, the URL for the 13th amendment works on my box.  But the URL for the video does not, so I would double-check that we're using a working video link.

**Comment by nedtwigg** [comment]
We're so close!!  Travis and I are both getting errors, and I believe it has to do with different fonts on our machine vs yours...

- show the 13th amendment
    Travis: Expected image to match or be a close match to snapshot but was 6.450745033112583% different from snapshot (18702 differing pixels).
    Me: Expected image to be the same size as the snapshot (960x302), but was different (960x257)

app-spec-ts-show-the-13-th-amendment-1-diff

- show some video captions
    Travis: Expected image to be the same size as the snapshot (960x1800), but was different (960x1845).
    Me: Expected image to be the same size as the snapshot (960x1800), but was different (960x1665).
app-spec-ts-show-the-13-th-amendment-1-diff

Also, at present https://node.mytake.org/api/images/o_dRqrNJ62wzlgLilTrLxkHqGmvAS9qTpa4z4pjyFqA=_54-86_0-218.png is failing with `{"message":"Canvas is not a constructor","error":{}}`

**Comment by WebsByTodd** [comment]
Aha! The font is `Merriweather`. I'm pretty sure I installed it on the node server a long time ago, although a quick poke around in `/usr/share/fonts` turned up 0 results. Can you install this font on your box and on CI?

The issue on the node server was that the dev dependencies in `package.json` were not being installed into `node_modules` because `$NODE_ENV` is set to `production`. See issue #213 . Since the code checks the environment variable and I was unsure of all the repercussions of changing it, I just moved all `devDependencies` into `dependencies` in `package.json` and ran `npm install` for now. Also in recent days I changed a `tsconfig.json` compiler option which prevented the build output from being emitted. I reverted that. Node server is now working identical to my local build.

https://node.mytake.org/api/images/vrhLapmIbWECYassLC2Umf7Z16fusYgWWGhTP7KgIYU=_5839.620-5949.290.png

https://node.mytake.org/api/images/o_dRqrNJ62wzlgLilTrLxkHqGmvAS9qTpa4z4pjyFqA=_54-86_0-218.png

**Comment by nedtwigg** [comment]
From [this article about node-canvas 1.x](https://medium.com/@adamhooper/fonts-in-node-canvas-bbf0b6b0cabf):

> Pango handles the tricky task of putting text in the right place. If you use node-canvas without Pango, you’ll get blocky and uneven text.
>
> node-canvas can install without Pango. Avoid that.
>
> Follow the node-canvas instructions: install pango before installing node-canvas. On Mac OS X, brew install pango. On Ubuntu, apt install libpango1.0-dev.
>
> If you installed node-canvas after installing Pango, reinstall node-canvas: rm -r node_modules/canvas && npm install canvas

Then it goes on to describe how to install fonts, but says that it will be outdated when node-canvas 2.x arrives.  And indeed, it seems that [node-canvas 2.x has added an API for fonts](https://github.com/Automattic/node-canvas/#registerfont):

```typescript
const { registerFont, createCanvas } = require('canvas')
registerFont('comicsans.ttf', { family: 'Comic Sans' })

const canvas = createCanvas(500, 500)
const ctx = canvas.getContext('2d')

ctx.font = '12px "Comic Sans"'
ctx.fillText('Everyone hates this font :(', 250, 10)
```

Aside from that, I see we are resolving calls with `toDataURL()`.  That made sense when we were embedding images into an email, but does it make sense now that we have a dedicated image server?  Maybe we should use [`createPNGStream()`](https://github.com/Automattic/node-canvas/#canvascreatepngstream)?

Regardless, I added the instructions into travis to `apt-get install libcairo2-dev libpango1.0-dev`.  Next I'm going to try hooking up the Merriweather font.

**Comment by nedtwigg** [comment]
As an aside: after `Fixed fonts in node-canvas so they don't depend on the system's fonts`, I tried clearing the cache, and found that the build actually couldn't complete without the cache.  So I upgraded some deps until we could build from clean.

**Comment by nedtwigg** [comment]
Huzzah!!  LGTM, press the merge button when you're satisfied @WebsByTodd

**Pull request merged**
