### PR TITLE
Feat/login modal

### PR DESCRIPTION
**Pull request by WebsByTodd**
Show a login modal when a logged-out user clicks a bookmark

### CODE REVIEW

**Comment by WebsByTodd** [comment]
@nedtwigg we can either use this at the basis for our sync-up or you can review/merge at will.

**Comment by nedtwigg** [comment]
If you do `POST {Routes.API_LOGIN}` with this (can use jsweet, or your own type, no preference from me):

https://github.com/mytakedotorg/mytakedotorg/blob/27dbec3b904efce8d330e866bd23e1aa993ae367/client/src/main/java/java2ts/LoginApi.java#L25-L29

For the `kind` field, you should use `use`.  The idea is that `login` is clicking the "Login" button at top right, and `use` is "I'm not just logging in, I'm performing an action which will immediately use the user".  There is also `newsletter` for the "Keep me up to date" use-case.

You will always get this structure back from the server with all fields non-null.

https://github.com/mytakedotorg/mytakedotorg/blob/27dbec3b904efce8d330e866bd23e1aa993ae367/client/src/main/java/java2ts/LoginApi.java#L34-L36

Besides that json body, you may also get some `set-cookie` headers that the browser should handle for you

The logic driving this lives here:

https://github.com/mytakedotorg/mytakedotorg/blob/27dbec3b904efce8d330e866bd23e1aa993ae367/server/src/main/java/auth/Accounts.java#L88-L105

It's not well-tested on my side, but it is wired up.  I have a meeting at 9:15am PST, I hope to be ready to integrate together by 10am PST.

**Comment by nedtwigg** [comment]
The previous commit confirms that the unauthenticated user flow is working.  The confirmation email is not, but this should be enough to start integration.

**Comment by nedtwigg** [comment]
I haven't implemented "refresh-might-fix" yet, just FYI.

**Pull request merged**
