### PR TITLE
Feature/upgrade react

### PR DESCRIPTION
**Pull request by WebsByTodd**

### CODE REVIEW

**Comment by WebsByTodd** [comment]
@nedtwigg server tests are failing here. Any insight?

```
> Task :server:test

auth.AuthUserTest > required FAILED
    java.lang.IllegalStateException at AuthUserTest.java:52

auth.AuthUserTest > optional FAILED
    java.lang.IllegalStateException at AuthUserTest.java:52

auth.TinfoilLoginTest > classMethod FAILED
    java.lang.IllegalStateException

auth.LoginLogoutTest > classMethod FAILED
    java.lang.IllegalStateException

auth.CreateAccountTest > classMethod FAILED
    java.lang.IllegalStateException

common.FoundationMigrationModuleTest > testReplace FAILED
    java.lang.IllegalStateException at FoundationMigrationModuleTest.java:43

common.ModsTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.DiscourseAuthTest > test FAILED
    java.lang.AssertionError at DiscourseAuthTest.java:60

controllers.ProfileTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.TakeReactionTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.TakeEmailTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.SharesTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.DbPlayground > demo FAILED
    java.lang.IllegalStateException at DbPlayground.java:31

controllers.FoundationTest > contentTypeJson FAILED
    java.lang.AssertionError at FoundationTest.java:31

controllers.DraftsTest > classMethod FAILED
    java.lang.IllegalStateException

controllers.TakesTest > classMethod FAILED
    java.lang.IllegalStateException

30 tests completed, 16 failed
```

`AuthUserTest.java:52` is the return statement of this method
```
	private static RequestSpecification givenUser(String username) {
		Account account = new Account();
		account.setId(-1); // not used
		account.setUsername(username);
		account.setEmail("unused@email.com");
		return AuthModuleHarness.givenUser(app.app(), account);
	}
```

**Comment by nedtwigg** [comment]
Probably `./gradlew dockerDown`, then try again.  It's because your test docker's disk filled up.

**Comment by WebsByTodd** [comment]
No luck, still failing on my box. But I see you were able to fix the snapshots and get CI to pass. Please review this and merge when you approve.

**Comment by nedtwigg** [comment]
The server port is hardcoded, so you can only run one server at a time.  The unit tests will fail if a server is running somewhere else, maybe `./gradlew --stop` to kill any `runDev` that might be running in the background.

**Pull request merged**
