### PR TITLE
Delete the sketch directory

### PR DESCRIPTION
**Pull request by nedtwigg**
I think the design is stale, but I'll let you decide, Todd. Btw, I can't find SVG assets for either of our logos (leaves or tree). If you know where they are, I think it would be good to put them in `_imgs`.

### CODE REVIEW

**Comment by hattersv** [comment]
Hi- can you remove me from the capital one account please?  Thank you!

**Comment by WebsByTodd** [comment]
No svg for the small logo, I used the Mac paint program for that. Attached that along with the large logo svg.

**Comment by nedtwigg** [comment]
Awesome, thanks! Can you find a link to the Mac paint program in question?

**Comment by WebsByTodd** [comment]
Yes, https://trybestapps.com/paint-pro/

**Pull request merged**
