### PR TITLE
Integrate the jest tests into CI

### PR DESCRIPTION
**Pull request by nedtwigg**

### CODE REVIEW

**Comment by nedtwigg** [comment]
Heya!  We're currently using two different versions of node:

**Comment by nedtwigg** [comment]
Heya!  We're currently using two versions of node:

https://github.com/mytakedotorg/mytakedotorg/blob/43f968c12039304a191a4d2e2e13915d93143964/client/build.gradle#L72

https://github.com/mytakedotorg/mytakedotorg/blob/43f968c12039304a191a4d2e2e13915d93143964/node/build.gradle#L42

If possible, it would be great to consolidate these to the latest LTS, 12.18.0.  We also have pretty old packages:

```
client> npm audit
  found 1806 vulnerabilities (1152 low, 77 moderate, 576 high, 1 critical
node> npm audit
  found 30316 vulnerabilities (21183 low, 20 moderate, 9112 high, 1 critical) in 1151 scanned packages
```

it would be good to update them.  The node tests are hanging for me, if we fix them, we can revert d4fab95e43fe19cebefeda910ba74af5c748af4a

This would make our whole build super-duper modern.

**Comment by nedtwigg** [comment]
Looks like the CI failure might be Spotless' old version of Prettier choking on a recent Typescript feature.  Feel free to comment-out this section if it helps:

https://github.com/mytakedotorg/mytakedotorg/blob/de0048ac7076436e7ba9b0df258691335e64871c/client/build.gradle#L20-L30

We can add it back when we do the Prettier 2.0+ upgrade.

**Comment by WebsByTodd** [comment]
https://img.youtube.com/vi/bKinkVeaC_8/0.jpg is 404ing, which causes the node server to fail on startup. `bKinkVeaC_8` is the Clinton, Bush, Perot debate from 10/19/92, which I think you've been working on recently but I'm not sure if that's related.

Still, the node server shouldn't fail if an image url 404s, especially since it depends on youtube's api. Is there a backup image we can use in the case of a 404?

**Comment by nedtwigg** [comment]
I disabled Spotless on the Typescript (having a problem which is easier to fix by upgrading to Prettier 2.x, which ought to be a new PR).  The 404 problem was solved by merging-in master to get the latest videos.  True it shouldn't 404, but handling a mutable foundation is a much harder problem than assuming that it is immutable, so I think we should put it for now.

**Comment by nedtwigg** [comment]
Awesome @WebsByTodd!  I think this is ready to merge.  If you don't have any local changes on any branches, then I'd like to take this opportunity to:

- [ ] Switch to AGPL with correct copyright headers
- [ ] Reformat with Prettier 2.0

I'll wait for an okay from you, and then I'll do it and rebase all the open PRs.

**Pull request merged**
